# Generated by Django 5.0.2 on 2024-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='body',
            field=models.TextField(default='Lanati'),
        ),
    ]
